# Generated by Django 3.1.4 on 2020-12-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarteIdentitate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('carte_identitate_img', models.ImageField(upload_to='static/images_upload/CI')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.TextField(max_length=50)),
                ('prenume', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('parola', models.TextField(max_length=30)),
            ],
        ),
    ]
