# Generated by Django 3.1.4 on 2020-12-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LEXBOXapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Utilizatori',
        ),
    ]
